//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeachersSurvey.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbServeySystemEntities : DbContext
    {
        public DbServeySystemEntities()
            : base("name=DbServeySystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblAnswerLine> TblAnswerLine { get; set; }
        public virtual DbSet<TblAnswers> TblAnswers { get; set; }
        public virtual DbSet<TblQuestions> TblQuestions { get; set; }
        public virtual DbSet<TblTeacher> TblTeacher { get; set; }
    }
}
